java servlet auth my tenant
Azure-Samples/ms-identity-java-servlet-webapp-authentication pull request #1
Opened 2020-12-22 23:32 UTC by idg-sam

2020-12-23 23:36 UTC, derisen commented on AppCreationScripts/sample.json
> +      "Service": "N/A",
You can omit the "Service" field entirely. It will slightly customize the generated README to a sign-in only sample

2020-12-23 23:41 UTC, derisen commented on README.md
> +  - azure
we can use `msal-java` now : )

2020-12-23 23:42 UTC, derisen commented on README.md
> +1. This Web application uses the **MSAL for Java** to sign in users to their own Azure AD tenant and obtains an [ID Token](https://docs.microsoft.com/azure/active-directory/develop/id-tokens) from **
typo "Web"

2020-12-23 23:44 UTC, derisen commented on README.md
> +   - In the **Redirect URI (optional)** section, select **Web** in the combo-box and enter the following redirect URI: `http://localhost:8080/ms-identity-java-servlet-webapp-authentication/auth_redir
we should remove "(optional)" here

2020-12-23 23:47 UTC, derisen commented on README.md
> +This sample shows how to use **MSAL4J** to sign in users into your Azure AD tenant.
just to prevent confusion, can we use "MSAL for Java" instead of "MSAL4J" (or whatever name we used above)

2020-12-23 23:52 UTC, derisen commented
LGTM Sam! Left some comments for the README

2020-12-24 00:02 UTC, kalyankrishna1 commented on src/main/java/com/microsoft/azuresamples/authentication/TokenDetailsServlet.java
> +        final String[] exClaims = {"iat", "exp", "nbf", "uti", "aio"};
>exClaims [](start = 23, length = 8)

better to work with included claim names. as random claims will keep showing up always

2020-12-24 00:04 UTC, kalyankrishna1 commented on README.md
> +- Follow the instructions on the next page to sign in with an account in the Azure AD tenant.
always mention the consent prompt in some detail like, "In the subsequent screen, you would be presented with the consent prompt, where blah blah..

2020-12-24 00:19 UTC, kalyankrishna1 commented on src/main/java/com/microsoft/azuresamples/authentication/AuthenticationFilter.java
> +public class AuthenticationFilter implements Filter {
>AuthenticationFilter [](start = 13, length = 20)

What exactly is this class about, do the devs copy it as is to their code

2020-12-24 00:19 UTC, kalyankrishna1 commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +public class AuthHelper {
>AuthHelper [](start = 13, length = 10)

What exactly is this class about, do the devs copy it as is to their code.
The methods of this class should be well commented too

2020-12-24 00:20 UTC, kalyankrishna1 commented on src/main/java/com/microsoft/azuresamples/authentication/MsalAuthSession.java
> +public class MsalAuthSession implements Serializable {
>MsalAuthSession [](start = 13, length = 15)

What exactly is this class about, do the devs copy it as is to their code

2020-12-24 00:20 UTC, kalyankrishna1 commented on src/main/java/com/microsoft/azuresamples/authentication/TokenDetailsServlet.java
> +public class TokenDetailsServlet extends HttpServlet {
>TokenDetailsServlet [](start = 13, length = 19)

What exactly is this class about, do the devs copy it as is to their code and how to use the code here to extract other claims from the id token

2020-12-24 00:21 UTC, kalyankrishna1 approved these changes
:shipit:

2020-12-24 00:22 UTC, derisen approved these changes

2020-12-24 00:22 UTC, kalyankrishna1 commented on README.md
> +Were we successful in addressing your learning objective? Consider taking a moment to [share your experience with us](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR73pcsbpb
>https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR73pcsbpbxNJuZCMKN0lURpUM0dYSFlIMzdHT0o3NlRNVFpJSzcwRVMxRyQlQCN0PWcu [](start = 118, length = 140)

the link is for Python sample?

2020-12-24 00:36 UTC, Shama-K approved these changes
LGTM. Left some comments for the README.
Thanks.

2020-12-24 00:36 UTC, Shama-K commented on README.md
> +- After signing out, click the link to `ID Token Details` to observe that the app displays a `401: unauthorized` error instead of the ID token claims when the user is not authorized.
After sign-out, link to **ID Token Details** is not displayed.

2020-12-24 00:36 UTC, Shama-K commented on README.md
> +> :information_source: Did the sample not work for you as expected? Did you encounter issues trying this sample? Then please reach out to us using the [GitHub Issues](../issues) page.
GitHub Issues link is not working here. It's working under [community-help-and-support](https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/tree/idgsam#community-help-and-support)

2021-01-06 22:41 UTC, sangonzal requested changes
Looks good overall! A couple of suggestions. 

Consider using the Intellij code formatter to standardize code formatting a bit (Ctrl + Alt + L on windows).

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AADRedirectServlet.java
> +
Should we be rethrowing the exception after logging it here?

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +            throws Exception {
It's considered a good practice to list the exact checked exceptions that a method might throw. In this case, it would be good to explicitly state that this method might throw MalformedUrlException

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +        msalAuth.setStateAndNonceAndPolicy(state, nonce, null);
If policy is always null, is it worth having?

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +        AuthorizationRequestUrlParameters parameters;
Is there a reason why you are defining parameters here but then setting on line 128?

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +            final IAuthenticationResult result = future.get();
```suggestion
            final IAuthenticationResult result = client.acquireTokenSilently(parameters).get();
```

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/AuthHelper.java
> +            final IAuthenticationResult result = future.get();
Applies to multiple places

2021-01-06 22:41 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/MsalAuthSession.java
> +    private IAuthenticationResult authResult = null;
If we are storing the tokenCache, is there a reason why we also need to keep the authResult?

2021-01-06 22:41 UTC, sangonzal commented on src/main/resources/authentication.properties
> +# b2c aad:
I think you can remove b2c from this comment

2021-01-08 08:30 UTC, jeevanbalanmanoj commented on src/main/java/com/microsoft/azuresamples/authentication/SignInStatusServlet.java
> +        view.forward(req, resp);
I just ran sonarlint locally and it gave a warning "Handle the following exceptions that could be thrown by "forward": ServletException, IOException."Any thoughts on this? 
Let's also try to add a sonarlint validation as part of our build process if you think that makes sense.

2021-01-22 00:17 UTC, navyasric commented on README.md
> +- A user account in your own Azure AD tenant. This sample will not work with a **personal Microsoft account**. If have not yet [created a user account](https://docs.microsoft.com/azure/active-directo
@idg-sam Why does it say this sample will not work for personal account? Is it because we configure it to use tenant ID? Do we plan to add another sample configured to sign in accounts in any tenant and personal account?

2021-01-22 00:40 UTC, navyasric commented on README.md
> +- [JDK Version 8 or higher](https://jdk.java.net/14/)
This link is going to jdk 14 which is not active. Can we update to point to jdk home page. jdk.java.net?

2021-01-22 00:40 UTC, navyasric commented on README.md
> +1. Find the resulting `.war` file in `./target/ms-identity-java-servlet-webapp-authentication.war` and upload it to your server.
Can we add more detail on how to upload this to Tomcat server specifically? Tomcat is commonly used and in our prerquisites. So we should at least detail the steps to move the war file to the right location in Tomcat and the command to start the Tomcat server.

2021-01-22 05:17 UTC, idg-sam commented on src/main/resources/authentication.properties
> +aad.scopes=openid profile offline_access
How do we use the parameters builder without scope(s)? IIRC it requires a scopes collection to be passed in, no?

2021-01-22 06:24 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authentication/AADRedirectServlet.java
> +
For whom to catch the re-thrown exception?
Also, compiler seems to complain that the doGet method signature doesn't allow different types of exceptions to be thrown (only choice is the default ones  in the interface definition or a generic exception)

2021-01-22 08:07 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authentication/AADRedirectServlet.java
> +
I have updated the app to catch and show an error page for displaying AAD-specific errors (those which originate from /authorize calls and from /token calls which the dev might have a particular interest in) and am leaving the rest of them uncaught for handling at another level (web.xml configs?).

2021-01-22 08:20 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authentication/MsalAuthSession.java
> +    private IAuthenticationResult authResult = null;
Good question -  I remember something about having difficulty with getting a specific account from the token cache without using some data from the authResult. Can you point me to the correct pattern for this?

2021-01-22 08:29 UTC, idg-sam commented on README.md
> +- A user account in your own Azure AD tenant. This sample will not work with a **personal Microsoft account**. If have not yet [created a user account](https://docs.microsoft.com/azure/active-directo
We will update the readmes to combine my org, any org, and anyorg+personal

2021-01-22 08:32 UTC, idg-sam commented on src/main/java/com/microsoft/azuresamples/authentication/SignInStatusServlet.java
> +        view.forward(req, resp);
I think build validation and tests are a good goal to work towards after we get our most urgent features out :)

2021-01-22 08:32 UTC, idg-sam commented on README.md
> +- [JDK Version 8 or higher](https://jdk.java.net/14/)
updating now.

2021-01-22 08:33 UTC, idg-sam commented on README.md
> +1. Find the resulting `.war` file in `./target/ms-identity-java-servlet-webapp-authentication.war` and upload it to your server.
updating now.

2021-01-22 12:32 UTC, idg-sam commented
I've done a refactor of the app. Please have a look over it again for me.

- Rewrote the README to be an "any sort of AAD app" README (single-tenant, any org, common, consumer).
- Code has been updated as per the code review comments here
- In-app feedback link that activates after sign in.

https://java-servlet-auth-test.azurewebsites.net/

2021-01-25 17:12 UTC, sangonzal commented on src/main/java/com/microsoft/azuresamples/authentication/MsalAuthSession.java
> +    private IAuthenticationResult authResult = null;
I think we can just store the username of the account returned in the authResult (which it seems you are already doing). When doing acquireTokenSilent, we use this username to get the right account from the cache, and then use that account to refresh tokens.

2021-02-16 11:51 UTC, closed without merging