Update graphsdk to v3 on all chapters & use BaseAuthenticationProvider
Azure-Samples/ms-identity-java-servlet-webapp-authentication pull request #4
Opened 2021-03-19 22:48 UTC by idg-sam

Actual use of GraphSDK is done on:

Chapter 2.1 - call graph
Chapter 3.2 - groups

All other chapters (except 1.2 - sign in B2C) all reference graph SDK in pom.xml and some classes, since they share a common code package, but do not actually use GraphSDK (unless user has ID token groups claim emission active).

2021-03-19 22:59 UTC, idg-sam commented
Also tagging @baywet and @jasonjoh from GraphSDK team for review as I couldn't add them from reviewer UI.

2021-03-22 12:37 UTC, baywet requested changes
Thanks for starting the update! A few recommendations, mainly for the authentication provider

2021-03-22 12:37 UTC, baywet commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/GraphHelper.java
> +            extends BaseAuthenticationProvider {
this class should have a constructor that accepts the client from MSAL, set it as a field and then use that client whenever a new token is requested.
We don't want to show people to build an authentication provider and subsequently a graph client on a single access token that will expire with no possibility to renew it.

2021-03-22 12:37 UTC, baywet commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/IdentityContextData.java
> +import com.microsoft.graph.models.Group;
```suggestion
```

2021-03-22 20:05 UTC, idg-sam commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/IdentityContextData.java
> +import com.microsoft.graph.models.Group;
I am using this type in the following method signature:

https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/pull/4/files/45f6faf9fff5c777d5574b4d862178b8070a22bd#diff-3a1e3bc6c22d3a4c50f20a2f865f06f594574f5ca5429cf0194a81787c797156L155

2021-03-22 20:08 UTC, baywet commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/IdentityContextData.java
> +import com.microsoft.graph.models.Group;
oh ok, nevermind me then :)

2021-03-22 20:30 UTC, idg-sam commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/GraphHelper.java
> +            extends BaseAuthenticationProvider {
I could link this method up to the [authorize() method in AuthHelper](https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/pull/4/files/45f6faf9fff5c777d5574b4d862178b8070a22bd#diff-f18de564020b4d78b3e07de943d3d8ce48f980fc5ed6c3ca4484e8960eb242f2L59). It will get AT using acquireTokenSilently (either through a valid token in the cache or refresh and get a new one using the RT), or trigger a new /authorize flow if neither are available.

In the existing sample demo, when a call is made to the `call_graph` endpoint, acquireTokenSilently() is called by way way of authorize() (as noted above), and a valid AT is obtained, and then the GraphClient is created with this AT. Since this is a web app, this is be done once per incoming request to that endpoint, and a valid token is obtained each time. After one use, the client is discarded and never used again.

2021-03-22 23:42 UTC, idg-sam commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/GraphHelper.java
> +            extends BaseAuthenticationProvider {
Tried implementing as per this recommendation and I am running into the following edge case problem:

1. Sign in interactively. This gets access token and ID token.
2. Parse ID token to verify nonce, and also mitigate [groups overage problem](https://docs.microsoft.com/azure/active-directory/develop/id-tokens#groups-overage-claim) if it happens.
3. Find groups overage has occurred (user has over 200 groups, won't fit in ID token, must be received from Graph).
4. Create Graph client to receive groups: Graph client automatically triggers AuthHelper.acquireTokenSilently(). This gets IDT and AT again.
5. ID token is parsed, which will repeat from step 3 again, due to groups overage.

A possible solution is to have another method that utilizes acquireTokenSilently() specifically for Graph client, one that doesn't parse the ID token again. This might cause other issues: e.g., the rest of the app won't know about token claims that might have been updated whenever Graph client does its call(s). Or, have Graph client maintain its own separate token acquisition and separate token cache.

Our demos until this point have demonstrated that whenever developers make any API call, they should acquireTokenSilently() before doing so in order to get a valid token for that call, so we could continue with that pattern here too.

@baywet  @kalyankrishna1 @sangonzal  please let me know your thoughts on how to proceed.

2021-03-23 12:24 UTC, baywet commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/GraphHelper.java
> +            extends BaseAuthenticationProvider {
@idg-sam thanks for this additional information.
could we at least pass in the IdentityContext to the authentication provider so it calls the "getAccessToken" method? I know this is only set once and won't ultimately solve the token expiration issue but at least we won't show the anti-pattern of having an authentication provider with a fixed token.
We might be able to refactor the identity context later on when a package like ms id web becomes available for java spring.

2021-03-23 18:01 UTC, idg-sam commented on 1-Authentication/sign-in/src/main/java/com/microsoft/azuresamples/msal4j/helpers/GraphHelper.java
> +            extends BaseAuthenticationProvider {
ok, perfect.

2021-03-24 11:45 UTC, baywet approved these changes
thanks for taking in the changes!

2021-03-25 00:44 UTC, idg-sam commented
changes approved by @baywet , all samples tested by @Shama-K and @derisen . Will rebase to main.

2021-03-25 00:44 UTC, merged